# Generated by Django 3.1.3 on 2020-12-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0005_auto_20201129_2224'),
        ('logs', '0006_auto_20201202_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inst.installation'),
        ),
    ]
