# Generated by Django 3.1.3 on 2020-12-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0006_auto_20201203_2041'),
        ('logs', '0009_auto_20201205_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inst.installation'),
        ),
    ]
