# Generated by Django 3.1.3 on 2020-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0005_auto_20201129_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='UIN',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
